#define COSSTYLE_LBRACE                           1
#define COSSTYLE_RBRACE                           2
#define COSSTYLE_COMMA                            3
#define COSSTYLE_ID                               4
#define COSSTYLE_DOT                              5
#define COSSTYLE_COLON                            6
#define COSSTYLE_STRING                           7
#define COSSTYLE_HEX                              8
#define COSSTYLE_NUMBER                           9
#define COSSTYLE_ADD                             10
#define COSSTYLE_SUB                             11
#define COSSTYLE_MUL                             12
#define COSSTYLE_DIV                             13
#define COSSTYLE_LPAREN                          14
#define COSSTYLE_RPAREN                          15
#define COSSTYLE_PERCENTAGE                      16
#define COSSTYLE_SEMI                            17
